### ISSUE TITLE
为啥要通过反射拿到DataBinding

### ISSUE THREAD

**Issue by JasonYinH** [oooo7777777/VLibrary#1]
通过反射拿到DataBinding而不用DataBindingUtil.setContentView

**Comment by oooo7777777** [comment]
> 通过反射拿到DataBinding而不用DataBindingUtil.setContentView

可以不通过反射去拿，可是那样需要使用构造方法或者抽象方法获取LayoutRes资源。
我为了不写这个所以用的反射。
